'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1), _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")> _
Partial Public NotInheritable Class Sheet1
  Inherits Microsoft.Office.Tools.Excel.Worksheet

  Friend WithEvents OrdersListObject As Microsoft.Office.Tools.Excel.ListObject

  Friend WithEvents InvoicesListObject As Microsoft.Office.Tools.Excel.ListObject

  Friend WithEvents List1 As Microsoft.Office.Tools.Excel.ListObject

  Friend WithEvents Chart_2 As Microsoft.Office.Tools.Excel.Chart

  Friend WithEvents Label1 As Microsoft.Office.Tools.Excel.Controls.Label

  Friend WithEvents CompanyListBox As Microsoft.Office.Tools.Excel.Controls.ListBox

  Friend WithEvents Northwind2007DataSet As CustomerDashboard.Northwind2007DataSet

  Friend WithEvents TableAdapterManager As CustomerDashboard.Northwind2007DataSetTableAdapters.TableAdapterManager

  Friend WithEvents CustomersTableAdapter As CustomerDashboard.Northwind2007DataSetTableAdapters.CustomersTableAdapter

  Friend WithEvents CustomersBindingSource As System.Windows.Forms.BindingSource

  Private components As System.ComponentModel.IContainer

  Friend WithEvents OrdersTableAdapter As CustomerDashboard.Northwind2007DataSetTableAdapters.OrdersTableAdapter

  Friend WithEvents OrdersBindingSource As System.Windows.Forms.BindingSource

  Friend WithEvents InvoicesTableAdapter As CustomerDashboard.Northwind2007DataSetTableAdapters.InvoicesTableAdapter

  Friend WithEvents InvoicesBindingSource As System.Windows.Forms.BindingSource

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Public Sub New()
    MyBase.New("Sheet1", "Sheet1")
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Protected Overrides Sub Initialize()
    MyBase.Initialize()
    Globals.Sheet1 = Me
    Global.System.Windows.Forms.Application.EnableVisualStyles()
    Me.InitializeCachedData()
    Me.InitializeControls()
    Me.InitializeComponents()
    Me.InitializeData()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Protected Overrides Sub FinishInitialization()
    Me.OnStartup()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Protected Overrides Sub InitializeDataBindings()
    Me.BeginInitialization()
    Me.BindToData()
    Me.EndInitialization()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub InitializeCachedData()
    If (Me.DataHost Is Nothing) Then
      Return
    End If
    If Me.DataHost.IsCacheInitialized Then
      Me.DataHost.FillCachedData(Me)
    End If
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub InitializeData()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub BindToData()
    Me.OrdersListObject.SetDataBinding(Me.OrdersBindingSource, "", "Order ID", "Order Date", "Shipped Date")
    Me.InvoicesListObject.SetDataBinding(Me.InvoicesBindingSource, "", "Invoice ID", "Invoice Date", "Due Date", "Amount Due")
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
  Private Sub StartCaching(ByVal MemberName As String)
    Me.DataHost.StartCaching(Me, MemberName)
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
  Private Sub StopCaching(ByVal MemberName As String)
    Me.DataHost.StopCaching(Me, MemberName)
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
  Private Function IsCached(ByVal MemberName As String) As Boolean
    Return Me.DataHost.IsCached(Me, MemberName)
  End Function

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub BeginInitialization()
    Me.BeginInit()
    Me.OrdersListObject.BeginInit()
    Me.InvoicesListObject.BeginInit()
    Me.List1.BeginInit()
    Me.Chart_2.BeginInit()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub EndInitialization()
    Me.Chart_2.EndInit()
    Me.List1.EndInit()
    Me.InvoicesListObject.EndInit()
    Me.OrdersListObject.EndInit()
    Me.EndInit()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub InitializeControls()
    Me.OrdersListObject = New Microsoft.Office.Tools.Excel.ListObject(Me.ItemProvider, Me.HostContext, "Sheet1:OrdersListObject", Me, "OrdersListObject")
    Me.InvoicesListObject = New Microsoft.Office.Tools.Excel.ListObject(Me.ItemProvider, Me.HostContext, "Sheet1:InvoicesListObject", Me, "InvoicesListObject")
    Me.List1 = New Microsoft.Office.Tools.Excel.ListObject(Me.ItemProvider, Me.HostContext, "Sheet1:List1", Me, "List1")
    Me.Chart_2 = New Microsoft.Office.Tools.Excel.Chart(Me.ItemProvider, Me.HostContext, "Sheet1:Chart 2", Me, "Chart_2")
    Me.Label1 = New Microsoft.Office.Tools.Excel.Controls.Label(Me.ItemProvider, Me.HostContext, "19C96EBE517C911422719AAD1A4EAE2DABB531", "19C96EBE517C911422719AAD1A4EAE2DABB531", Me, "Label1")
    Me.CompanyListBox = New Microsoft.Office.Tools.Excel.Controls.ListBox(Me.ItemProvider, Me.HostContext, "2E9BE6E142D75E24D792AC592C53A9BE5DEB82", "2E9BE6E142D75E24D792AC592C53A9BE5DEB82", Me, "CompanyListBox")
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub InitializeComponents()
    Me.components = New System.ComponentModel.Container
    If (Me.Northwind2007DataSet Is Nothing) Then
      'Instantiate the object if not yet loaded from the data cache.
      Me.Northwind2007DataSet = New CustomerDashboard.Northwind2007DataSet
    End If
    Me.TableAdapterManager = New CustomerDashboard.Northwind2007DataSetTableAdapters.TableAdapterManager
    Me.CustomersTableAdapter = New CustomerDashboard.Northwind2007DataSetTableAdapters.CustomersTableAdapter
    Me.CustomersBindingSource = New System.Windows.Forms.BindingSource(Me.components)
    Me.OrdersTableAdapter = New CustomerDashboard.Northwind2007DataSetTableAdapters.OrdersTableAdapter
    Me.OrdersBindingSource = New System.Windows.Forms.BindingSource(Me.components)
    Me.InvoicesTableAdapter = New CustomerDashboard.Northwind2007DataSetTableAdapters.InvoicesTableAdapter
    Me.InvoicesBindingSource = New System.Windows.Forms.BindingSource(Me.components)
    CType(Me.Northwind2007DataSet, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.CustomersBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.OrdersListObject, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.OrdersBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.InvoicesListObject, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.InvoicesBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.List1, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.Chart_2, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
    '
    'Label1
    '
    Me.Label1.Name = "Label1"
    Me.Label1.Text = "Company: "
    '
    'CompanyListBox
    '
    Me.CompanyListBox.DataSource = Me.CustomersBindingSource
    Me.CompanyListBox.DisplayMember = "Company"
    Me.CompanyListBox.Name = "CompanyListBox"
    Me.CompanyListBox.ValueMember = "ID"
    '
    'Northwind2007DataSet
    '
    Me.Northwind2007DataSet.DataSetName = "Northwind2007DataSet"
    Me.Northwind2007DataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
    '
    'TableAdapterManager
    '
    Me.TableAdapterManager.BackupDataSetBeforeUpdate = False
    Me.TableAdapterManager.CustomersTableAdapter = Me.CustomersTableAdapter
    Me.TableAdapterManager.InvoicesTableAdapter = Me.InvoicesTableAdapter
    Me.TableAdapterManager.OrdersTableAdapter = Me.OrdersTableAdapter
    Me.TableAdapterManager.UpdateOrder = CustomerDashboard.Northwind2007DataSetTableAdapters.TableAdapterManager.UpdateOrderOption.InsertUpdateDelete
    '
    'CustomersTableAdapter
    '
    Me.CustomersTableAdapter.ClearBeforeFill = True
    '
    'CustomersBindingSource
    '
    Me.CustomersBindingSource.DataMember = "Customers"
    Me.CustomersBindingSource.DataSource = Me.Northwind2007DataSet
    '
    'OrdersTableAdapter
    '
    Me.OrdersTableAdapter.ClearBeforeFill = True
    '
    'OrdersBindingSource
    '
    Me.OrdersBindingSource.DataMember = "New_CustomerOnOrders"
    Me.OrdersBindingSource.DataSource = Me.CustomersBindingSource
    '
    'InvoicesTableAdapter
    '
    Me.InvoicesTableAdapter.ClearBeforeFill = True
    '
    'InvoicesBindingSource
    '
    Me.InvoicesBindingSource.DataMember = "New_OrderInvoice"
    Me.InvoicesBindingSource.DataSource = Me.OrdersBindingSource
    '
    'Sheet1
    '
    CType(Me.Northwind2007DataSet, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.CustomersBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.OrdersListObject, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.OrdersBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.InvoicesListObject, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.InvoicesBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.List1, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.Chart_2, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
    Me.Label1.BindingContext = Me.BindingContext
    Me.CompanyListBox.BindingContext = Me.BindingContext
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
  Private Function NeedsFill(ByVal MemberName As String) As Boolean
    Return Me.DataHost.NeedsFill(Me, MemberName)
  End Function

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Protected Overrides Sub OnShutdown()
    Me.Chart_2.Dispose()
    Me.List1.Dispose()
    Me.InvoicesListObject.Dispose()
    Me.OrdersListObject.Dispose()
    MyBase.OnShutdown()
  End Sub
End Class

Partial Friend NotInheritable Class Globals

  Private Shared _Sheet1 As Sheet1

  Friend Shared Property Sheet1() As Sheet1
    Get
      Return _Sheet1
    End Get
    Set(ByVal value As Sheet1)
      If (_Sheet1 Is Nothing) Then
        _Sheet1 = value
      Else
        Throw New System.NotSupportedException
      End If
    End Set
  End Property
End Class
