'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0), _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")> _
Partial Public NotInheritable Class ThisDocument
  Inherits Microsoft.Office.Tools.Word.Document
  Implements Microsoft.VisualStudio.Tools.Office.IOfficeEntryPoint

  Friend WithEvents ActionsPane As Microsoft.Office.Tools.ActionsPane

  Friend WithEvents RichTextContentControl1 As Microsoft.Office.Tools.Word.RichTextContentControl

  Friend WithEvents RichTextContentControl2 As Microsoft.Office.Tools.Word.RichTextContentControl

  Friend WithEvents RichTextContentControl3 As Microsoft.Office.Tools.Word.RichTextContentControl

  <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0")> _
  Friend WithEvents ThisApplication As Microsoft.Office.Interop.Word.Application

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Public Sub New()
    MyBase.New("ThisDocument", "ThisDocument")
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Protected Overrides Sub Initialize()
    MyBase.Initialize()
    Me.ThisApplication = Me.GetHostItem(Of Microsoft.Office.Interop.Word.Application)(GetType(Microsoft.Office.Interop.Word.Application), "Application")
    Globals.ThisDocument = Me
    Global.System.Windows.Forms.Application.EnableVisualStyles()
    Me.InitializeCachedData()
    Me.InitializeControls()
    Me.InitializeComponents()
    Me.InitializeData()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Protected Overrides Sub FinishInitialization()
    Me.OnStartup()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Protected Overrides Sub InitializeDataBindings()
    Me.BeginInitialization()
    Me.BindToData()
    Me.EndInitialization()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub InitializeCachedData()
    If (Me.DataHost Is Nothing) Then
      Return
    End If
    If Me.DataHost.IsCacheInitialized Then
      Me.DataHost.FillCachedData(Me)
    End If
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub InitializeData()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub BindToData()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
  Private Sub StartCaching(ByVal MemberName As String)
    Me.DataHost.StartCaching(Me, MemberName)
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
  Private Sub StopCaching(ByVal MemberName As String)
    Me.DataHost.StopCaching(Me, MemberName)
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
  Private Function IsCached(ByVal MemberName As String) As Boolean
    Return Me.DataHost.IsCached(Me, MemberName)
  End Function

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub BeginInitialization()
    Me.BeginInit()
    Me.ActionsPane.BeginInit()
    Me.RichTextContentControl1.BeginInit()
    Me.RichTextContentControl2.BeginInit()
    Me.RichTextContentControl3.BeginInit()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub EndInitialization()
    Me.RichTextContentControl3.EndInit()
    Me.RichTextContentControl2.EndInit()
    Me.RichTextContentControl1.EndInit()
    Me.ActionsPane.EndInit()
    Me.EndInit()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub InitializeControls()
    Me.ActionsPane = New Microsoft.Office.Tools.ActionsPane(Me.ItemProvider, Me.HostContext, "ActionsPane", Me, "ActionsPane")
    Me.RichTextContentControl1 = New Microsoft.Office.Tools.Word.RichTextContentControl(Me.ItemProvider, Me.HostContext, "671940139", Me, "RichTextContentControl1")
    Me.RichTextContentControl2 = New Microsoft.Office.Tools.Word.RichTextContentControl(Me.ItemProvider, Me.HostContext, "671940140", Me, "RichTextContentControl2")
    Me.RichTextContentControl3 = New Microsoft.Office.Tools.Word.RichTextContentControl(Me.ItemProvider, Me.HostContext, "671940143", Me, "RichTextContentControl3")
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Private Sub InitializeComponents()
    CType(Me.ActionsPane, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.RichTextContentControl1, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.RichTextContentControl2, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me.RichTextContentControl3, System.ComponentModel.ISupportInitialize).BeginInit()
    CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
    '
    'ActionsPane
    '
    Me.ActionsPane.AutoSize = False
    Me.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange
    '
    'ThisDocument
    '
    CType(Me.ActionsPane, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.RichTextContentControl1, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.RichTextContentControl2, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me.RichTextContentControl3, System.ComponentModel.ISupportInitialize).EndInit()
    CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
  End Sub

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
  Private Function NeedsFill(ByVal MemberName As String) As Boolean
    Return Me.DataHost.NeedsFill(Me, MemberName)
  End Function

  '''
  <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
   Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0"), _
   Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)> _
  Protected Overrides Sub OnShutdown()
    Me.RichTextContentControl3.Dispose()
    Me.RichTextContentControl2.Dispose()
    Me.RichTextContentControl1.Dispose()
    Me.ActionsPane.Dispose()
    MyBase.OnShutdown()
  End Sub
End Class

'''
<Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0")> _
Partial Friend NotInheritable Class Globals

  '''
  Private Sub New()
    MyBase.New()
  End Sub

  Private Shared _ThisDocument As ThisDocument

  Private Shared _ThisRibbonCollection As ThisRibbonCollection

  Friend Shared Property ThisDocument() As ThisDocument
    Get
      Return _ThisDocument
    End Get
    Set(ByVal value As ThisDocument)
      If (_ThisDocument Is Nothing) Then
        _ThisDocument = value
      Else
        Throw New System.NotSupportedException
      End If
    End Set
  End Property

  Friend Shared ReadOnly Property Ribbons() As ThisRibbonCollection
    Get
      If (_ThisRibbonCollection Is Nothing) Then
        _ThisRibbonCollection = New ThisRibbonCollection
      End If
      Return _ThisRibbonCollection
    End Get
  End Property
End Class

'''
<Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "9.0.0.0")> _
Partial Friend NotInheritable Class ThisRibbonCollection
  Inherits Microsoft.Office.Tools.Ribbon.RibbonReadOnlyCollection
End Class
